trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    goals: 'clean package'
    mavenPomFile: 'pom.xml'

- script: |
    echo "Listing build output files"
    ls -R $(System.DefaultWorkingDirectory)
  displayName: "Check build directory"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/**/target/*.war'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
